import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import { Container, SSRProvider } from "@/components/bootstrap";
import NavBar from "./NavBar";

export const metadata: Metadata = {
  title: "Next Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SSRProvider>
          <NavBar/>
          <main>
            <Container className="py-4">
              {children}
            </Container>
          </main>
         
        </SSRProvider>

      </body>
    </html>
  );
}
